# Generated by Django 4.2.7 on 2023-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(upload_to='ogrenciResim', verbose_name='Öğrenci Fotoğrafı: ')),
                ('isim', models.CharField(max_length=100, verbose_name='Öğrenci Adı: ')),
                ('soyad', models.CharField(max_length=100, verbose_name='Öğrenci Soyad: ')),
                ('hakkinda', models.TextField(max_length=500, verbose_name='Öğrenci Hakkında: ')),
            ],
        ),
    ]
